# Generated by Django 3.2 on 2021-04-22 18:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='published',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2021, 4, 22, 18, 30, 38, 540925, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
