# Generated by Django 3.2 on 2021-04-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
