# Generated by Django 3.2 on 2021-04-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_solution_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='risks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solution',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
